### ISSUE TITLE
Merge forks

### ISSUE THREAD

**Issue by iBobik** [chrisjrn/kaas#12]
There are tho other forks. I think it will be better to collaborate on maintaining of just one project. Don't you think?

@BobertForever @lgleasain

**Comment by rob0rt** [comment]
I originally forked because I had a different set of things I needed to accomplish then what was originally set out for in KaaS, and some additional set of functionality that didn't make sense in the main repo.

As for core functionality I didn't really add anything or change anything so I'm not sure what I'd be able to contribute.

**Comment by lgleasain** [comment]
Mine is a similar situation.  I wrote it to support streaming via websockets to Wearscript to mirror my speaker notes on Google Glass.

**Comment by rob0rt** [comment]
@lgleasain amusingly, that's almost exactly what mine did except with polling and not web sockets :+1:

**Comment by chrisjrn** [comment]
Hi all,

So as you've probably guessed, there's not a great deal of maintenance
going on here at the moment. This is because Keynote 6's AppleScript
support is a pretty big regression on Keynote 5. Namely, I can't get the
current slide from a playing slideshow.

Any idea how this is going on the current version of Keynote? I can't
upgrade because Yosemite :)

Anyway -- I'm open to merging in any forks/pull requests as provided, but I
won't be merging either of the current forks wholesale. Send me pull
requests if you have useful features!

--Chris
